<main class="container py-4 py-md-5">
    <div class="page-toolbar mb-3"><a href="<?= site_url('mikrotik-profiles?router_id=' . (int) $router_id) ?>" class="back-button"><i class="fa-solid fa-arrow-left"></i><span>Kembali</span></a></div>
    <section class="menu-shell monitoring-shell"><div class="menu-heading"><h1><?= $mode === 'create' ? 'Tambah' : 'Edit' ?> PPP Profile</h1><p>Perubahan langsung diterapkan ke MikroTik dan tidak disimpan pada database aplikasi.</p></div>
        <?php $this->load->view('../../views/layout/flash'); ?>
        <?php if ($api_error): ?><div class="glass-panel p-3 mt-3 text-warning"><?= html_escape($api_error) ?></div><?php endif; ?>
        <form method="post" action="<?= $action ?>" class="glass-panel p-3 mt-3"><input type="hidden" name="profile_id" value="<?= html_escape($profile['.id'] ?? '') ?>"><div class="row g-3">
            <div class="col-md-6"><label class="form-label">Router <span class="text-danger">*</span></label><select name="router_id" id="profileRouter" class="form-select" required <?= $mode === 'edit' ? 'disabled' : '' ?>><?php foreach ($routers as $router): ?><option value="<?= (int) $router['id'] ?>" <?= (int) $router_id === (int) $router['id'] ? 'selected' : '' ?>><?= html_escape($router['name'] . ' — ' . $router['host']) ?></option><?php endforeach; ?></select><?php if ($mode === 'edit'): ?><input type="hidden" name="router_id" value="<?= (int) $router_id ?>"><?php endif; ?></div>
            <div class="col-md-6"><label class="form-label">Nama Profile <span class="text-danger">*</span></label><input name="name" class="form-control" maxlength="64" value="<?= html_escape($profile['name'] ?? '') ?>" required <?= $mode === 'edit' && !empty($profile['_usage_count']) ? 'readonly' : '' ?>><?php if ($mode === 'edit' && !empty($profile['_usage_count'])): ?><div class="form-text text-warning"><i class="fa-solid fa-lock me-1"></i>Nama dikunci karena profile dipakai oleh <?= (int) $profile['_usage_count'] ?> PPP Secret: <?= html_escape(implode(', ', $profile['_usage_examples'])) ?>.</div><?php endif; ?></div>
            <div class="col-md-6"><label class="form-label">Local Address</label><input name="local_address" class="form-control" value="<?= html_escape($profile['local-address'] ?? '') ?>" placeholder="10.10.10.1"></div>
            <div class="col-md-6"><label class="form-label">Remote Address / Pool</label><select name="remote_address" class="form-select"><option value="">Default / kosong</option><?php foreach ($pools as $pool): if (empty($pool['name'])) continue; ?><option value="<?= html_escape($pool['name']) ?>" <?= ($profile['remote-address'] ?? '') === $pool['name'] ? 'selected' : '' ?>><?= html_escape($pool['name'] . (!empty($pool['ranges']) ? ' — ' . $pool['ranges'] : '')) ?></option><?php endforeach; ?></select></div>
            <div class="col-12"><label class="form-label">Rate Limit</label><input name="rate_limit" class="form-control font-monospace" maxlength="100" value="<?= html_escape($profile['rate-limit'] ?? '') ?>" placeholder="20M/20M atau format burst lengkap"><div class="form-text">Kosong berarti unlimited. Mendukung K, M, G dan format burst RouterOS.</div></div>
            <div class="col-md-6"><label class="form-label">DNS Server</label><input name="dns_server" class="form-control" value="<?= html_escape($profile['dns-server'] ?? '') ?>" placeholder="8.8.8.8,1.1.1.1"></div>
            <div class="col-md-3"><label class="form-label">Only One</label><select name="only_one" class="form-select"><?php foreach (['yes'=>'Yes','no'=>'No','default'=>'Default'] as $key=>$label): ?><option value="<?= $key ?>" <?= ($profile['only-one'] ?? 'default') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div>
            <div class="col-md-3"><label class="form-label">Change TCP MSS</label><select name="change_tcp_mss" class="form-select"><?php foreach (['yes'=>'Yes','no'=>'No','default'=>'Default'] as $key=>$label): ?><option value="<?= $key ?>" <?= ($profile['change-tcp-mss'] ?? 'default') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div>
        </div><button type="submit" class="back-button border-0 mt-3"><i class="fa-solid fa-save"></i><span>Simpan ke MikroTik</span></button></form>
    </section>
</main>
<?php if ($mode === 'create'): ?><script>document.getElementById('profileRouter').addEventListener('change',function(){window.location.href='<?= site_url('mikrotik-profiles/create?router_id=') ?>'+encodeURIComponent(this.value);});</script><?php endif; ?>
