<main class="container py-4 py-md-5">
    <div class="page-toolbar mb-3"><a href="<?= site_url('/') ?>" class="back-button"><i class="fa-solid fa-arrow-left"></i><span>Kembali</span></a><a href="<?= site_url('mikrotik-profiles/create?router_id=' . (int) $selected_router_id) ?>" class="back-button"><i class="fa-solid fa-plus"></i><span>Tambah Profile</span></a></div>
    <section class="menu-shell monitoring-shell">
        <div class="menu-heading"><h1><i class="fa-solid fa-sliders me-2"></i>PPP Profile MikroTik</h1><p>CRUD profile dilakukan langsung melalui API RouterOS tanpa menyimpan data ke database aplikasi.</p></div>
        <?php $this->load->view('../../views/layout/flash'); ?>
        <form method="get" action="<?= site_url('mikrotik-profiles') ?>" class="glass-panel p-3 mt-3"><div class="row g-2 align-items-end"><div class="col-md-8"><label class="form-label">Router</label><select name="router_id" class="form-select" onchange="this.form.submit()"><?php foreach ($routers as $router): ?><option value="<?= (int) $router['id'] ?>" <?= (int) $selected_router_id === (int) $router['id'] ? 'selected' : '' ?>><?= html_escape($router['name'] . ' — ' . $router['host']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><a href="<?= current_url() . '?router_id=' . (int) $selected_router_id ?>" class="back-button justify-content-center"><i class="fa-solid fa-rotate"></i><span>Refresh API</span></a></div></div></form>
        <?php if ($api_error): ?><div class="glass-panel p-3 mt-3 text-warning"><i class="fa-solid fa-triangle-exclamation me-2"></i><?= html_escape($api_error) ?></div><?php endif; ?>
        <div class="card glass-card shadow-sm mt-3"><div class="card-body table-responsive"><table class="table table-bordered table-striped table-nowrap"><thead><tr><th>Nama</th><th>Dipakai Secret</th><th>Local Address</th><th>Remote Address</th><th>Rate Limit</th><th>DNS</th><th>Only One</th><th>TCP MSS</th><th width="170">Action</th></tr></thead><tbody>
            <?php if (!$profiles): ?><tr><td colspan="9" class="text-center text-muted">Tidak ada profile atau router belum dipilih.</td></tr><?php endif; ?>
            <?php foreach ($profiles as $profile): ?><tr><td><strong><?= html_escape($profile['name'] ?? '-') ?></strong><small class="d-block text-muted"><?= html_escape($profile['.id']) ?></small></td><td><span class="monitoring-badge <?= !empty($profile['_usage_count']) ? 'is-offline' : 'is-online' ?>"><?= (int) ($profile['_usage_count'] ?? 0) ?> Secret</span><?php if (!empty($profile['_usage_examples'])): ?><small class="d-block text-muted mt-1" title="<?= html_escape(implode(', ', $profile['_usage_examples'])) ?>"><?= html_escape(implode(', ', array_slice($profile['_usage_examples'], 0, 2))) ?><?= $profile['_usage_count'] > 2 ? '…' : '' ?></small><?php endif; ?></td><td><?= html_escape($profile['local-address'] ?? '-') ?></td><td><?= html_escape($profile['remote-address'] ?? '-') ?></td><td><?= html_escape($profile['rate-limit'] ?? '-') ?></td><td><?= html_escape($profile['dns-server'] ?? '-') ?></td><td><?= html_escape($profile['only-one'] ?? 'default') ?></td><td><?= html_escape($profile['change-tcp-mss'] ?? 'default') ?></td><td><div class="d-flex gap-2"><a class="monitoring-action text-decoration-none" href="<?= site_url('mikrotik-profiles/edit?router_id=' . (int) $selected_router_id . '&profile_id=' . rawurlencode($profile['.id'])) ?>">Edit</a><?php if (empty($profile['_usage_count'])): ?><form method="post" action="<?= site_url('mikrotik-profiles/delete') ?>"><input type="hidden" name="router_id" value="<?= (int) $selected_router_id ?>"><input type="hidden" name="profile_id" value="<?= html_escape($profile['.id']) ?>"><button type="submit" class="monitoring-action border-0" data-confirm="Hapus PPP Profile <?= html_escape($profile['name'] ?? '') ?> langsung dari MikroTik?">Delete</button></form><?php else: ?><button type="button" class="monitoring-action border-0 opacity-50" disabled title="Profile masih digunakan PPP Secret">Delete</button><?php endif; ?></div></td></tr><?php endforeach; ?>
        </tbody></table></div></div>
    </section>
</main>
