<?php
$months=app_language()==='en'?[1=>'January',2=>'February',3=>'March',4=>'April',5=>'May',6=>'June',7=>'July',8=>'August',9=>'September',10=>'October',11=>'November',12=>'December']:[1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'];
$money=function($value){return 'Rp '.number_format((float)$value,0,',','.');};
$en=app_language()==='en'; $t=function($id,$english)use($en){return $en?$english:$id;};
$printYears=array_keys($print_periods); rsort($printYears); $defaultPrintYear=in_array($year,$printYears,true)?$year:($printYears[0]??$year); $defaultPrintMonths=$print_periods[$defaultPrintYear]??[]; rsort($defaultPrintMonths); $defaultPrintMonth=$defaultPrintMonths[0]??(int)date('n');
?>
<main class="container py-4 py-md-5"><div class="page-toolbar mb-3"><a href="<?= site_url('/') ?>" class="back-button"><i class="fa-solid fa-arrow-left"></i><span><?= $t('Kembali','Back') ?></span></a><div class="toolbar-actions"><button type="button" class="back-button border-0" data-profit-print-open><i class="fa-solid fa-file-pdf"></i><span><?= $t('Cetak / PDF','Print / PDF') ?></span></button><a href="<?= site_url('financial-reports') ?>" class="back-button"><i class="fa-solid fa-chart-column"></i><span><?= $t('Laporan Keuangan','Financial Report') ?></span></a><a href="<?= site_url('profit-sharing/settings') ?>" class="back-button"><i class="fa-solid fa-sliders"></i><span><?= $t('Pengaturan','Settings') ?></span></a></div></div>
<section class="menu-shell monitoring-shell"><div class="menu-heading"><h1><i class="fa-solid fa-handshake me-2"></i><?= $t('Bagi Hasil','Profit Sharing') ?></h1><p><?= $t('Distribusi penghasilan bersih bulanan berdasarkan pengaturan yang berlaku pada setiap periode.','Monthly net income distribution based on the settings effective for each period.') ?></p></div>
<form method="get" class="glass-panel p-3 mt-3"><div class="row g-2 align-items-end"><div class="col-md-10"><label class="form-label">Tahun</label><select name="year" class="form-select"><?php foreach($years as $item): ?><option value="<?= $item ?>" <?= $year===$item?'selected':'' ?>><?= $item ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="filter-submit-button w-100 justify-content-center"><i class="fa-solid fa-filter"></i><span>Tampilkan</span></button></div></div></form>
<div class="row g-3 mt-1"><div class="col-md-6 col-xl-3"><div class="glass-panel result-box"><div class="text-muted">Laba Bersih <?= $year ?></div><h3><?= $money($totals['net']) ?></h3></div></div><div class="col-md-6 col-xl-3"><div class="glass-panel result-box"><div class="text-muted">Total Pihak Pertama</div><h3 class="text-info"><?= $money($totals['party_1']) ?></h3></div></div><div class="col-md-6 col-xl-3"><div class="glass-panel result-box"><div class="text-muted">Total Pihak Kedua</div><h3 class="text-success"><?= $money($totals['party_2']) ?></h3></div></div><div class="col-md-6 col-xl-3"><div class="glass-panel result-box"><div class="text-muted">Cadangan Perusahaan</div><h3 class="text-warning"><?= $money($totals['reserve']) ?></h3></div></div></div>
<div class="glass-panel p-3 mt-3"><i class="fa-solid fa-circle-info text-info me-2"></i>Perubahan pengaturan hanya berlaku mulai bulan efektif dan tidak mengubah pembagian pada bulan sebelumnya.</div>
<div class="card glass-card shadow-sm mt-3"><div class="card-header glass-header"><i class="fa-solid fa-table-list me-2"></i>Distribusi Bagi Hasil <?= $year ?></div><div class="card-body table-responsive"><table class="table table-bordered table-striped table-nowrap"><thead><tr><th>Bulan</th><th class="text-end">Laba Bersih</th><th class="text-end">Pihak Pertama</th><th class="text-end">Pihak Kedua</th><th class="text-end">Cadangan</th></tr></thead><tbody><?php foreach($rows as $row): $s=$row['setting']; ?><tr><td><?= $months[$row['month']] ?></td><td class="text-end"><?= $money($row['net']) ?></td><td class="text-end text-info"><?= html_escape($s['party_1_name']) ?> (<?= (float)$s['party_1_percent'] ?>%)<br><strong><?= $money($row['party_1']) ?></strong></td><td class="text-end text-success"><?= html_escape($s['party_2_name']) ?> (<?= (float)$s['party_2_percent'] ?>%)<br><strong><?= $money($row['party_2']) ?></strong></td><td class="text-end text-warning"><?= $row['reserve_percent'] ?>%<br><strong><?= $money($row['reserve']) ?></strong></td></tr><?php endforeach; ?></tbody><tfoot><tr class="fw-bold"><td>Total <?= $year ?></td><td class="text-end"><?= $money($totals['net']) ?></td><td class="text-end text-info"><?= $money($totals['party_1']) ?></td><td class="text-end text-success"><?= $money($totals['party_2']) ?></td><td class="text-end text-warning"><?= $money($totals['reserve']) ?></td></tr></tfoot></table></div></div></section></main>
<div class="profit-print-modal" data-profit-print-modal data-print-periods="<?= html_escape(json_encode($print_periods)) ?>" data-month-labels="<?= html_escape(json_encode($months)) ?>" aria-hidden="true"><div class="profit-print-backdrop" data-profit-print-close></div><section class="profit-print-panel" role="dialog" aria-modal="true" aria-labelledby="profitPrintTitle"><header><div><small><?= $t('Laporan Bagi Hasil','Profit Sharing Report') ?></small><h2 id="profitPrintTitle"><?= $t('Pilih Periode Laporan','Select Report Period') ?></h2></div><button type="button" data-profit-print-close aria-label="<?= $t('Tutup','Close') ?>"><i class="fa-solid fa-xmark"></i></button></header><form action="<?= site_url('profit-sharing/print') ?>" method="get" target="_blank" data-profit-print-form><div class="profit-print-fields"><label><span><?= $t('Bulan','Month') ?></span><select name="month" class="form-select" required data-profit-print-month><?php foreach($defaultPrintMonths as $number): ?><option value="<?= $number ?>" <?= $number===$defaultPrintMonth?'selected':'' ?>><?= $months[$number] ?></option><?php endforeach; ?></select></label><label><span><?= $t('Tahun','Year') ?></span><select name="year" class="form-select" required data-profit-print-year><?php foreach($printYears as $item): ?><option value="<?= $item ?>" <?= $defaultPrintYear===$item?'selected':'' ?>><?= $item ?></option><?php endforeach; ?></select></label></div><?php if(!$printYears): ?><p class="profit-print-empty"><i class="fa-solid fa-circle-info"></i><?= $t('Belum ada periode pembayaran yang dapat dicetak.','There are no payment periods available to print.') ?></p><?php endif; ?><input type="hidden" name="autoprint" value="1"><footer><button type="button" class="profit-print-cancel" data-profit-print-close><?= $t('Batal','Cancel') ?></button><button type="submit" class="profit-print-submit" <?= !$printYears?'disabled':'' ?>><i class="fa-solid fa-download"></i><span><?= $t('Unduh Laporan','Download Report') ?></span></button></footer></form></section></div>
