<?php
$en = app_language() === 'en';
$t = function ($id, $english) use ($en) { return $en ? $english : $id; };
$months = $en
    ? [1=>'January',2=>'February',3=>'March',4=>'April',5=>'May',6=>'June',7=>'July',8=>'August',9=>'September',10=>'October',11=>'November',12=>'December']
    : [1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'];
$money = function ($value) { return 'Rp ' . number_format((float) $value, 0, ',', '.'); };
$logo = app_setting('logo_path', 'assets/img/logo.jpeg');
if ($logo && !preg_match('#^https?://#i', $logo)) $logo = base_url(ltrim($logo, '/'));
?>
<!doctype html><html lang="<?= $en ? 'en' : 'id' ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $t('Laporan Bagi Hasil','Profit Sharing Report') ?> <?= $months[$month].' '.$year ?></title>
<style>
@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{margin:0;background:#e8edf3;color:#172033;font:11px Arial,Helvetica,sans-serif}.report{width:100%;max-width:1120px;min-height:190mm;margin:22px auto;padding:14mm;background:#fff;box-shadow:0 14px 45px #1b2b4230}.header{display:flex;align-items:center;gap:16px;padding-bottom:13px;border-bottom:3px solid #176da5}.logo{width:64px;height:64px;object-fit:contain}.company{flex:1}.company h1{margin:0;color:#0d4369;font-size:21px}.company p,.doc-title p{margin:4px 0 0;color:#677587;font-size:9px}.doc-title{text-align:right}.doc-title h2{margin:0;font-size:17px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.meta div{padding:8px 10px;border:1px solid #dbe3ec;border-radius:6px;background:#f7f9fc}.meta span,.summary small{display:block;color:#718096;font-size:8px;text-transform:uppercase;letter-spacing:.07em}.meta strong{display:block;margin-top:3px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px}.summary article{padding:10px 12px;border-left:4px solid #1684c2;background:#f2f7fb}.summary article:nth-child(3){border-color:#209565}.summary article:last-child{border-color:#d69b27;background:#fff9ed}.summary strong{display:block;margin-top:5px;font-size:14px}.note{margin-bottom:12px;padding:8px 10px;border:1px solid #dfe6ee;background:#fafbfd;color:#536174;font-size:9px}.section-title{margin:12px 0 7px;color:#164d73;font-size:11px;text-transform:uppercase;letter-spacing:.06em}table{width:100%;border-collapse:collapse;font-size:9px}thead{display:table-header-group}tr{page-break-inside:avoid}th{padding:7px 6px;color:#fff;background:#176da5;border:1px solid #10567f;text-align:left}td{padding:6px;border:1px solid #dbe2e9}tbody tr:nth-child(even){background:#f7f9fb}.right{text-align:right}.totals td{font-weight:bold;background:#eaf4fa;border-top:2px solid #176da5}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:100px;margin-top:22px;text-align:center}.signatures div{padding:0 30px}.signatures p{margin:0 0 42px}.signatures strong{display:block;padding-top:5px;border-top:1px solid #455468}.footer{display:flex;justify-content:space-between;margin-top:14px;padding-top:7px;border-top:1px solid #dce3eb;color:#7a8796;font-size:8px}.print-actions{position:fixed;right:18px;bottom:18px;display:flex;gap:8px}.print-actions button{padding:10px 16px;border:0;border-radius:8px;color:#fff;font-weight:bold;cursor:pointer;background:#176da5;box-shadow:0 5px 18px #0003}.print-actions .close{background:#526274}@media print{html,body{background:#fff!important}.report,.report *{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.report{max-width:none;min-height:auto;margin:0;padding:0;box-shadow:none}.print-actions{display:none!important}}@media(max-width:700px){.report{margin:0;padding:18px;min-width:900px}.print-actions{left:10px;right:auto}}
</style></head><body><main class="report">
<header class="header"><?php if($logo): ?><img class="logo" src="<?= html_escape($logo) ?>" alt="Logo"><?php endif; ?><div class="company"><h1><?= html_escape(app_setting('isp_name','ISP BATARA NET')) ?></h1><p><?= html_escape(app_setting('isp_address','')) ?></p></div><div class="doc-title"><h2><?= $t('LAPORAN BAGI HASIL BULANAN','MONTHLY PROFIT SHARING REPORT') ?></h2><p><?= html_escape($report_number) ?></p></div></header>
<section class="meta"><div><span><?= $t('Periode','Period') ?></span><strong><?= $months[$month].' '.$year ?></strong></div><div><span><?= $t('Tanggal Cetak','Print Date') ?></span><strong><?= date('d/m/Y H:i') ?></strong></div><div><span><?= $t('Disiapkan Oleh','Prepared By') ?></span><strong><?= html_escape($prepared_by) ?></strong></div><div><span><?= $t('Jumlah Periode','Period Count') ?></span><strong>1 <?= $t('bulan','month') ?></strong></div></section>
<section class="summary"><article><small><?= $t('Laba Bersih','Net Income') ?></small><strong><?= $money($totals['net']) ?></strong></article><article><small><?= $t('Total Pihak Pertama','First Party Total') ?></small><strong><?= $money($totals['party_1']) ?></strong></article><article><small><?= $t('Total Pihak Kedua','Second Party Total') ?></small><strong><?= $money($totals['party_2']) ?></strong></article><article><small><?= $t('Cadangan Perusahaan','Company Reserve') ?></small><strong><?= $money($totals['reserve']) ?></strong></article></section>
<div class="note"><strong><?= $t('Dasar perhitungan:','Calculation basis:') ?></strong> <?= $t('Pembagian dihitung dari laba bersih bulanan menggunakan persentase yang berlaku pada masing-masing periode.','Distribution is calculated from monthly net income using the percentages effective in each period.') ?></div>
<h3 class="section-title"><?= $t('Rincian Distribusi Bagi Hasil','Profit Sharing Distribution Details') ?></h3><table><thead><tr><th><?= $t('Bulan','Month') ?></th><th class="right"><?= $t('Laba Bersih','Net Income') ?></th><th class="right"><?= $t('Pihak Pertama','First Party') ?></th><th class="right"><?= $t('Pihak Kedua','Second Party') ?></th><th class="right"><?= $t('Cadangan','Reserve') ?></th></tr></thead><tbody><?php foreach($rows as $row): $s=$row['setting']; ?><tr><td><?= $months[$row['month']] ?></td><td class="right"><?= $money($row['net']) ?></td><td class="right"><?= html_escape($s['party_1_name']) ?> (<?= (float)$s['party_1_percent'] ?>%)<br><strong><?= $money($row['party_1']) ?></strong></td><td class="right"><?= html_escape($s['party_2_name']) ?> (<?= (float)$s['party_2_percent'] ?>%)<br><strong><?= $money($row['party_2']) ?></strong></td><td class="right"><?= (float)$row['reserve_percent'] ?>%<br><strong><?= $money($row['reserve']) ?></strong></td></tr><?php endforeach; ?></tbody><tfoot><tr class="totals"><td><?= $t('TOTAL PERIODE','PERIOD TOTAL') ?></td><td class="right"><?= $money($totals['net']) ?></td><td class="right"><?= $money($totals['party_1']) ?></td><td class="right"><?= $money($totals['party_2']) ?></td><td class="right"><?= $money($totals['reserve']) ?></td></tr></tfoot></table>
<section class="signatures"><div><p><?= $t('Disusun oleh,','Prepared by,') ?></p><strong><?= html_escape($prepared_by) ?></strong></div><div><p><?= $t('Disetujui oleh,','Approved by,') ?></p><strong><?= $t('Administrator / Pimpinan','Administrator / Management') ?></strong></div></section><footer class="footer"><span><?= html_escape(app_setting('isp_name','ISP BATARA NET')) ?> - <?= $t('Laporan internal perusahaan','Internal company report') ?></span><span><?= $t('Dicetak otomatis oleh sistem billing','Automatically generated by the billing system') ?></span></footer></main>
<div class="print-actions"><button type="button" onclick="window.print()"><?= $t('Cetak / Simpan PDF','Print / Save PDF') ?></button><button type="button" class="close" onclick="window.close()"><?= $t('Tutup','Close') ?></button></div><?php if(!empty($auto_print)): ?><script>window.addEventListener('load',function(){window.setTimeout(function(){window.print();},350);});</script><?php endif; ?></body></html>
