<?php
$en=app_language()==='en';
$t=function($id,$english)use($en){return $en?$english:$id;};
$form=$editing?:['id'=>'','effective_month'=>date('Y-m-01'),'party_1_name'=>'','party_1_percent'=>75,'party_2_name'=>'','party_2_percent'=>14];
?>
<main class="container py-4 py-md-5">
<div class="page-toolbar mb-3"><a href="<?= site_url('profit-sharing') ?>" class="back-button"><i class="fa-solid fa-arrow-left"></i><span><?= $t('Kembali ke Bagi Hasil','Back to Profit Sharing') ?></span></a></div>
<section class="menu-shell monitoring-shell"><div class="menu-heading"><h1><i class="fa-solid fa-sliders me-2"></i><?= $t('Pengaturan Bagi Hasil','Profit Sharing Settings') ?></h1><p><?= $t('Atur nama pihak dan persentase berdasarkan bulan mulai berlaku. Riwayat bulan sebelumnya tidak akan berubah.','Set party names and percentages by effective month. Previous months will remain unchanged.') ?></p></div>
<form action="<?= site_url('profit-sharing/settings/save') ?>" method="post" class="glass-panel p-3 mt-3"><input type="hidden" name="id" value="<?= (int)$form['id'] ?>"><div class="row g-3 align-items-end">
<div class="col-md-2"><label class="form-label"><?= $t('Mulai Berlaku','Effective Month') ?></label><input type="month" name="effective_month" class="form-control" value="<?= html_escape(substr($form['effective_month'],0,7)) ?>" required></div>
<div class="col-md-3"><label class="form-label"><?= $t('Nama Pihak Pertama','First Party Name') ?></label><input name="party_1_name" class="form-control" value="<?= html_escape($form['party_1_name']) ?>" required></div>
<div class="col-md-1"><label class="form-label"><?= $t('Persen','Percent') ?></label><input type="number" name="party_1_percent" class="form-control" min="0" max="100" step="0.01" value="<?= (float)$form['party_1_percent'] ?>" required></div>
<div class="col-md-3"><label class="form-label"><?= $t('Nama Pihak Kedua','Second Party Name') ?></label><input name="party_2_name" class="form-control" value="<?= html_escape($form['party_2_name']) ?>" required></div>
<div class="col-md-1"><label class="form-label"><?= $t('Persen','Percent') ?></label><input type="number" name="party_2_percent" class="form-control" min="0" max="100" step="0.01" value="<?= (float)$form['party_2_percent'] ?>" required></div>
<div class="col-md-2"><button class="back-button border-0 w-100 justify-content-center"><i class="fa-solid fa-floppy-disk"></i><span><?= $editing?$t('Perbarui','Update'):$t('Simpan','Save') ?></span></button><?php if($editing): ?><a href="<?= site_url('profit-sharing/settings') ?>" class="btn btn-sm btn-outline-secondary w-100 mt-2"><?= $t('Batal','Cancel') ?></a><?php endif; ?></div></div></form>
<div class="card glass-card shadow-sm mt-3"><div class="card-header glass-header"><?= $t('Riwayat Pengaturan','Settings History') ?></div><div class="card-body table-responsive"><table class="table table-bordered table-striped table-nowrap"><thead><tr><th><?= $t('Mulai Berlaku','Effective Month') ?></th><th><?= $t('Pihak Pertama','First Party') ?></th><th><?= $t('Persentase','Percentage') ?></th><th><?= $t('Pihak Kedua','Second Party') ?></th><th><?= $t('Persentase','Percentage') ?></th><th><?= $t('Cadangan','Reserve') ?></th><th><?= $t('Aksi','Actions') ?></th></tr></thead><tbody>
<?php foreach($settings as $item): $reserve=100-(float)$item['party_1_percent']-(float)$item['party_2_percent']; ?><tr><td><?= date('m/Y',strtotime($item['effective_month'])) ?></td><td><?= html_escape($item['party_1_name']) ?></td><td><?= (float)$item['party_1_percent'] ?>%</td><td><?= html_escape($item['party_2_name']) ?></td><td><?= (float)$item['party_2_percent'] ?>%</td><td><?= $reserve ?>%</td><td><div class="table-action-group"><a href="<?= site_url('profit-sharing/settings?edit='.$item['id']) ?>" class="table-action-button is-edit" title="<?= $t('Edit','Edit') ?>"><i class="fa-solid fa-pen-to-square"></i><span><?= $t('Edit','Edit') ?></span></a><a href="<?= site_url('profit-sharing/settings/delete/'.$item['id']) ?>" class="table-action-button is-delete" data-confirm="<?= $t('Hapus pengaturan periode ini?','Delete these period settings?') ?>"><i class="fa-solid fa-trash-can"></i><span><?= $t('Hapus','Delete') ?></span></a></div></td></tr><?php endforeach; ?>
</tbody></table></div></div></section></main>
